name: Check README

on:
  pull_request:
    branches: [ main ]
    paths: [ .github/workflows/pr-readme.yml, pr/readme/**, crates/**, README.md ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check README
        run: ./pr/readme/check.py
